### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microservices-docker#1]
What you'll learn

- [x] The intro paragraph talking about creating 2 docker images and having 2 microsrevices on them can be reworked. Few points seem important for this guide: 
  - learn how to create `Dockerfiles` and how to use the `dockerifle-maven-plugin`, so this is to be stated first, along with building a Docker image. ie, You will learn how to create a Docker image using a `Dockerfile` and the `dockerfile-maven-plugin`. 
  - then mention about creating 2 Docker images from OL image. ie, You will create two images from the Open Liberty image and you will deploy two microservices on them? 
  - lastly, running the docker images with `docker run` cmd. ie, You can then run the Docker image instances in two containers using the `docker run` command. 

- [x] The `What is Docker` and `What is a container` sections seem repetitive from the other Docker guide. I think this guide can explain "what is a docker image", to be more relevant? Can then add links to the Docker pages and instructions, where they fit. 

Building your microservices

- [x] Some missing backticks for the service names and directory names

- [x] Don't think the detail explanation fo the `inventory` and `system` services are needed in this guide. Same with seeing what the endpoint provides. Just a brief description of the endpoints that will be used in this guide.

- [x] Not sure the heading fo this section fits, "Building your microservices" sounds like construction some micriserivices, but really, it is to compile and start the provided server with the services?

- [x] Somehow this section looks like "Try what you'll build".. but I think that's not the purpose. This section seems like to build the application, so you have things to work with in the later sections? If that's the case, you don't need to start the server, and as well, stop the server. 

Building your Docker images

- [x] Would be good to add a short paragraph to start off this section before the sub-sections. 

- [x] Next, you will be creating two Docker images for the inventory service and system service. 
=> "Next," is not needed here
=> I think this statement says, you will create two Docker images, one to run the `inventory` service and one to run the `system` service. Right? 

These are my review feedback for now. I think the guide is still being work. You can address those as you go along too. Will continue to review the guide when it's ready. Thanks.

**Comment by justineechen** [comment]
@gkwan-ibm 's feedback:

- [ ] 1. “You’ll learn paragraph …” may need to be reworded. I am not sure how to  say. It can be improved
- [ ] 2. “Building your microservices” section looks too detail
- [ ] 3. Dockfile should be formatted better and add comments for the COPY, at least which COPYs for setting up server, and which for the application
- [ ] 4. after replace system pom.xml, there may be better to have a subsection for mvn packages and docker images
- [ ] 5. there is a line not formatted good in system pom.xml

**Comment by justineechen** [comment]
@evelinec 

> Not sure the heading fo this section fits, "Building your microservices" sounds like construction some micriserivices, but really, it is to compile and start the provided server with the services?

- I updated this to "Checking out your microservices" for now.. it still sounds a little weird so I might come back to this, do you have any suggestions?

> Somehow this section looks like "Try what you'll build".. but I think that's not the purpose. This section seems like to build the application, so you have things to work with in the later sections? If that's the case, you don't need to start the server, and as well, stop the server.

- From initial discussions, we wanted to prove to the users that the microservices would work before we built the Docker image from them! We can rediscuss to see if we need to add this section.

@gkwan-ibm 
> 4. after replace system pom.xml, there may be better to have a subsection for mvn packages and docker images

- I updated and made a section named "Creating your docker image" but it seems redundant because the larger section is called "Building your docker image", let me know what you think or if you have suggestions to name this

**Comment by evelinec** [comment]
Couple things: 

- [ ] Add this statement to the beginning of the `Packaging your microservices` section: Navigate to the `start` directory to begin.
- [ ] Then perhaps `start/system and start/inventory` doesn't need the `start` directory
- [ ] I found this sentence incorrect? "Install Docker on the official instructions page." => perhaps you meant, "Install Docker by following the instructions on the official page."?

Others look good. Thanks.

**Comment by evelinec** [comment]
Changes look good. Closed.
