### ISSUE TITLE
Is <profile> for windowsExtension needed?

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-microservices-docker#12]
Check if <profile> for windowsExtension is needed for this guide, if not remove.

**Comment by gkwan-ibm** [comment]
yes, the exec for the maven plugin requires `.cmd` in the pom.xml to start/stop system service

**Comment by yeekangc** [comment]
I am sorry but I don't quite follow.  What part of the guide requires this and for what?

**Comment by yeekangc** [comment]
You meant for inventory to start system for testing?  Ok, we need to look into that further separately.

**Comment by gkwan-ibm** [comment]
yes, currently it is required unless we can find a better solution separately
