### ISSUE TITLE
Running process after going through the guide

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microservices-docker#14]
After going through the guide, ie, run the end-to-end test on the guide, and performed the last step to stop and remove the container, there's still a local running java process (of the application server) on the system. Running the `mvn liberty:stop-server` command kills it. Pls investigate.

**Comment by evelinec** [comment]
@justineechen @gkwan-ibm

**Comment by gkwan-ibm** [comment]
@evelinec would you retest the dev branch? The issue should be fixed.

**Comment by evelinec** [comment]
Tested end-to-end in the `start` directory. The problem doesn't exist anymore.
