### ISSUE TITLE
travisTest script feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microservices-docker#15]
- put “cd ../finish” in the pre step? 
- why running “killall -9 java” command in the test after “mvn clean install”?

**Comment by evelinec** [comment]
@justineechen @gkwan-ibm

**Comment by gkwan-ibm** [comment]
#14 was fixed, so the `cd ../finish` and `mvn clean install ...` may not need anymore

**Comment by justineechen** [comment]
Fixed the cd ../finish and created extra travisTestStart.sh script to test the start directory

**Comment by evelinec** [comment]
Feedback on the 7/23 test script changes: 
- The `travisTestStart.sh` script can be renamed to its purpose? ie, `travisTestServices.sh` because it's meant to test the provided services to make sure they're working properly? 
- The script description can be updated to "Travis CI test script  to test the services (provided in the `start` directory)"? 

Others look good.

**Comment by justineechen** [comment]
Thank you @evelinec ! I addressed those two just now ^

**Comment by evelinec** [comment]
Looks good. Closed.
