### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/draft-guide-microservices-docker#2]
- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide

---

- [x] Define test coverage and review with team (including guide contributor, if available)
- [x] Define detail test cases 
- [x] Consider corner cases targeting the specific guide
- [x] Consider different platform tests, ie, Mac, Windows, Linux
- [x] Consider corner cases UI tests
- [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
- [x] Consider testing the `curl` command for URL visits
- [x] Consider Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, Microclimate
- [x] Run Acrolink Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run with continuous daily builds

---

- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by proubatsis** [comment]
# General

> The starting point of the inventory service can be found at the http://localhost:9080/inventory/systems URL. It displays the current contents of the inventory.

URL should use port 9081.

> The system can be added to the inventory by visiting the http://localhost:9080/inventory/systems/localhost URL.

URL should use port 9081.

> In this case, you’re using the openliberty/open-liberty:javaee8 image as your parent image, which comes with the latest Open Liberty runtime.

This is a bit confusing considering that you use `FROM open-liberty`, maybe elaborate or change `FROM open-liberty` to `FROM openliberty/open-liberty:javaee8`.

> The openliberty/open-liberty:javaee8 parent image has a Dockerfile itself. The instructions in this Dockerfile will be executed along with the rest of the instructions in the inventory/Dockerfile that you just created.

That's not quite right. You will be pulling the `open-liberty` image from Docker Hub. You're not executing the instructions in its Dockerfile. The image has been built using a Dockerfile and pushed to Docker Hub. You are pulling the image from Docker Hub when you use `FROM` in your Dockerfile.

![image](https://user-images.githubusercontent.com/8409464/57464743-3cd1b200-724b-11e9-92b0-c5825629369e.png)

Remove spaces so that the formatting looks better.

> To access the application, point your browser to the http://localhost:9080/inventory/systems URL. As you might expect, these are empty since nothing is stored in the inventory yet.

The paragraph shows `9080`, but the link goes to `9081` when clicked on.

> Point your browser to the http://localhost:9080/inventory/systems/system-ip-address URL by replacing the system-ip-address with the value you obtained. You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system properties are automatically stored in the inventory. Go back to http://localhost:9080/inventory/systems and you see a new entry for localhost. For simplicity, only the OS name and username are shown here for each host. You can repeat this process for your own hostname or any other machine that is running the system service.

Same issue for both links in this paragraph.

> http://localhost:9080/inventory/systems/system-ip-address

This shouldn't be clickable since you need to substitute `system-ip-address`. Also, add an indicator to show it should be swapped similar to how it's done in the other guides.

> If the tests pass, you will see a similar output to the following:

You should show the output for both system and inventory.

> To stop your container, run the following command from the command line.

Two container**s**. It's probably also better to list the commands out on their own lines.

>  Run the docker logs rest-app command to view the container logs for any potential problems and double-check that your Dockerfile is correct. When you find the cause of the issue, remove the faulty container with the docker rm rest-app command, rebuild your image, and start the container again.

There is no container named `rest-app` in the guide, is the reader meant to replace `rest-app` with `system` or `inventory`?

> Nice work! You have just completed building a Docker image with two microservices in Open Liberty.

Built two docker images, not one.

# Diff

![image](https://user-images.githubusercontent.com/8409464/57468648-e4061780-7252-11e9-8207-0cc0becbbb19.png)

This should be the same in both finish and start

# Automation

There's no travisfile.

# Acrolinx

> An Docker image is a binary file

**A** Docker image...

> The COPY instruction needs to use the user id 1001 and group 0 because that is the user id that is set up in the base image, without this the files and directories copied over would be owned by root

Sentence is too long.

> Using Maven plugin to build your Docker images
Now that your microservices are complete and you have written your Dockerfiles, you will build your Docker images.

Use `plug-in` instead.

> To build your image, you need to have Docker installed. For installation instructions, see the Official Docker Docs.

Avoid causative "have".

> Point your browser to the http://localhost:9080/system/properties URL. This is the system service which shows the system properties of your local JVM.

Add a comma after `service`.

> Go back to http://localhost:9080/inventory/systems and you see a new entry for localhost. For simplicity, only the OS name and username are shown here for each host. You can repeat this process for your own hostname or any other machine that is running the system service.

`username` -> `user name` and `hostname` -> `host name`

**Comment by justineechen** [comment]
- [ ] This is a bit confusing considering that you use FROM open-liberty, maybe elaborate or change FROM open-liberty to FROM openliberty/open-liberty:javaee8.

**Comment by justineechen** [comment]
Addressed above issues in:
https://github.com/OpenLiberty/draft-guide-microservices-docker/commit/a8b6d47d2f24ac708ed3d5279691824de4fc009c
https://github.com/OpenLiberty/draft-guide-microservices-docker/commit/828cb0b0c14f5ee8b46ee49dd07d9eba38648460

**Comment by proubatsis** [comment]
# General

> to create a complete and executable version of the application

Maybe `to create a containerized version of the application` would work better here?

![image](https://user-images.githubusercontent.com/8409464/57798585-14e6c080-771b-11e9-91fb-a2892fe6b24b.png)

Should this be `Create the inventory/Dockerfile file`? Same feedback for the system Dockerfile.

> In this case, you’re using the openliberty image as your parent image

> The openliberty parent image has been built using a Dockerfile itself and pushed to Docker Hub.

Change `openliberty` to `open-liberty`.

> Finally, all .war files are copied over into inventory.war.

There should only be one war file in the target directory.

```
docker run -d --name system -p 9080:9080 system:latest
docker run -d --name inventory -p 9081:9081 inventory:latest
```

Specifying the `:latest` tag is not required.

![image](https://user-images.githubusercontent.com/8409464/57799877-0fd74080-771e-11e9-8550-cb6623d6f99b.png)

This link is not valid, it also doesn't open in a new tab.

![image](https://user-images.githubusercontent.com/8409464/57799940-35fce080-771e-11e9-8fb6-a4d2eb286925.png)

Hovering over this doesn't switch to the file.

![image](https://user-images.githubusercontent.com/8409464/57800025-59279000-771e-11e9-92b6-5dc4c0de8cca.png)

Are we bolding the parts to be replaced going forward?

> Nice work! You have just completed building a Docker image with two microservices in Open Liberty.

Built two docker images. Also, why "with" two microservices? Maybe "for" would be better in this context, I think the sentence needs to be re-worked a bit.

# Automation

Travis is not setup.

# Acrolinx

Next, you **will to retrieve** the system containers IP address.

Instead, your **containers appears** with an Exited status when you run the docker ps -a command.

**Comment by proubatsis** [comment]
>  Check the quality and presentation of guide according to Structure and Style Guideline

https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles#writing-tests

When using assertEquals(), expected and actual should be stored in separate variables.

>  Consider SEO title and description for the guides

The SEO description probably needs to be re-worked a bit, check one of the recently published guides to get an idea.

**Comment by justineechen** [comment]
> Should this be Create the inventory/Dockerfile file? Same feedback for the system Dockerfile.
I think that is convention for files with the same name in different directories: https://openliberty.io/guides/maven-multimodules.html#adding-dependencies-between-war-and-jar-modules

> Are we bolding the parts to be replaced going forward?
I will confirm with Andrew to see what Jay told him for the cloud guides

**Comment by DannyS03** [comment]
### **Grammatical** 

### **Getting started**
- [ ] The starting Java project, which you can find in the start directory, is a multi-module Maven project that’s made up of the system and inventory microservices. Each microservice resides in its own directory, start/system and start/inventory, respectively.
Checking out your microservices
- [ ] To try out the application using Maven, first, navigate to the start directory and then run the following Maven goals to build the application. Run it inside Open Liberty: 
- [ ] The system can be added to the inventory service by visiting the http://localhost:9081/inventory/systems/localhost URL.

### **Building your Docker images**
**Creating your Dockerfiles**

- [ ] **Description should be after the paragraph that contains the Dockerfiles hotspot.** A Dockerfile is a collection of instructions for building a Docker image that can then be run as a container. Every Dockerfile begins with a parent or base image on top of which various commands are run. For example, you can start your image from scratch and execute commands that download and install Java, or you can start from an image that already contains a Java installation.

- [ ] The FROM instruction initializes a new build stage, which indicates the parent image from the image that has been built. If you do not need a parent image, then you can use FROM scratch instruction, which makes your image a base image.

- [ ] In this case, you are using the open-liberty image as your parent image, which comes with the latest Open Liberty runtime. There are three different Open Liberty Docker image sets available on Docker Hub. You can learn more about them on the OpenLiberty Docker Images repository.

- [ ] The bootstrap.properties, server.env and server.xml files contain configuration information, such as http ports and features for the application. Finally, all .war files are copied over into inventory.war.
Running your microservices in Docker containers

### **Running your microservices in Docker containers**
- [ ] In this case, the address for system is 172.17.0.2. Note down the IP address for system in order to add the system properties to the inventory service.
Testing the application

### **Testing the application**
- [ ] The systemServiceIp is the same value that you retrieved in the previous section to manually add the system service into the inventory service. This value will also be passed in when you run the tests.

**Running the tests**
- [ ] If a problem occurs and your containers exit prematurely, the containers won’t appear in the container list that the docker ps command displays. Instead, your containers appear with an Exited status when running the docker ps -a command. Run the docker logs system and docker logs inventory commands to view the container logs for any potential problems, and double-check that your Dockerfiles are correct. When you find the cause of the issue, remove the faulty containers with the docker rm system and docker rm inventory commands. Then, rebuild your image and start the containers again.

**Comment by justineechen** [comment]
@DannyS03 
>  To try out the application using Maven, first, navigate to the start directory and then run the following Maven goals to build the application. Run it inside Open Liberty:

- `mvn install` builds the application and `mvn liberty:start-server` runs it so I think it's okay to keep those two phrases together and not separate run it inside open liberty when the command is still asking the users to run `mvn install`

**Comment by proubatsis** [comment]
@justineechen 

> If the tests pass, you will see a similar output to the following:

You should show the output for both system and inventory.

> To build your image, you need to have Docker installed. For installation instructions, see the Official Docker Docs.

Avoid causative "have".

> Finally, all .war files are copied over into inventory.war.

There should only be one war file in the target directory.

> Nice work! You have just built Docker images for two microservices in Open Liberty.

This sentence sounds a bit odd.

---

Automated builds are failing: https://travis-ci.org/OpenLiberty/draft-guide-microservices-docker

**Comment by DannyS03** [comment]
> @DannyS03
> 
> > To try out the application using Maven, first, navigate to the start directory and then run the following Maven goals to build the application. Run it inside Open Liberty:
> 
> * `mvn install` builds the application and `mvn liberty:start-server` runs it so I think it's okay to keep those two phrases together and not separate run it inside open liberty when the command is still asking the users to run `mvn install`

**Comment by DannyS03** [comment]
Changes look good!

**Comment by evelinec** [comment]
Pls ensure the automation tests are able to run with continuous daily builds.

**Comment by proubatsis** [comment]
Looks good
