### ISSUE TITLE
GK's feedback 2

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-microservices-docker#4]
- [x] description in the main content, suggest as following:
  - "Learn how to containerize your micoservices with Open Liberty by Docker and run them in isolated containers."
- What you’ll learn
  - [x] need to rewrite as following:
    - To accelerate your development, you may use the containerization technology to deploy and run your micoservices into isolated containers instead of different entire physical or virtual machines. 
    - Application containerization is to bundle an application with its entire environment, meaning all of its required libraries, dependencies, and configuration files, so that it can run in any containerization ecosystem, such as Docker, and it can also be deployed to Kubernetes.
    - You'll learn how to construct `Dockerfile`, how to create Docker images by using `docker build` command, and how to run the image in Docker container by using `docker run` command. 
    - The two microservices that you'll be working are called `system` and `inventory`. The `system` microservice returns the JVM system properties of the running container. The `inventory` microservice adds the properties from the `system` microservice to the inventory. This guide  demonstrates how both microservices can be run and communicate in different isolated containers.
- Packaging your microservices
  - [x] `cd start` is not necessary inside the green command box because the above statement already mention "navigate to the start directory"
  - [x] suggest remove `<package.file>` from the `<properties/>`; update `<packageFile/>` to specify the `.tar.gz` (beware the format); hotspot to  `<packageFile/>`
  - [x] the pom.xml need to be formatted better for `<summaryFile/>` and `<reportsDirectory/>`
  - [x] need a statement for the following between the statementst "In pom.xml..." and "The starting point ...":
     - the system and inventory microservices including the application WAR and server configuration files are archived into system/target/????.tar.gz and inventory/target/????.tar.gz.
  - [x] rephrase "The system can be added to the inventory by visiting the http://localhost:9081/inventory/systems/localhost URL." to
    - "The system properties of your localhost can be added to the inventory service by visiting the http://localhost:9081/inventory/systems/localhost URL."
- subsection "Creating your Dockerfiles"
  - [x] update the docker file as 
```FROM open-liberty
ADD --chown=1001:0 \
    target/inventory.tar.gz \
    /opt/ol
```
- subsection "Creating your Dockerfiles"
  - [x] reword the paragraph "The ADD instruction copies local..." as following (beware to hotspot; if hotspot tag not work, use hotspot line # is fine)
    - The `ADD` instruction  is structured as `ADD [option] <source> <destination>`. It copies local files and directories into the destination within your Docker image. If the source is an archive,  the `ADD` instruction will unpack it into the destination directory.  In this case, the inventory archived application file `inventory.tar.gz`, that was created from running `mvn install`, will be extracted to the destination directory `/opt/ol`.
  - [x] The statement "Finally, the inventory..." is not needed
  - Note: The add instruction in the system dockfile has no need to be in 3 lines

- subsection "Creating your Docker image"
  - [x] reword the 4 statements before the green docker build command because the "Official Docker Docs" and install docker already described at the beginning of the "Building your Docker images" section. May need to mention docker daemon should be started by a separate statement
  - [x] change `name:tag` to `name[:tag]`
  - [x] add following before the statement "To verify that ..."
    - because `[:tag]` is not specified, the latest version will be created by default.
  - [x] is it possible make the output "no wrap" and use scroll bar?
- Running your microservices in Docker containers
  - [x] should plural in following statement
    - "Make sure that your container is running and shows Up x seconds as its status:"
  - [x] is it possible make the output "no wrap" and use scroll bar?
  - [x]  "[system-ip-address]"  need backticks
  - [x] are you should "Linux" for all platforms?
  - [x] " ...and double-check..." can be an independent statement
  - [x] "When you find the cause of the issue, ....",  singular and plural not consistent 
- Testing the application
  - [x] make sure to use the word "application" and "microservice" consistent in this section and in the whole guide 
  - [ ] if reader tried the docker services, and run the tests,  testEmptyInventory() will fail
  - [x] is it possible make the output "no wrap" and use scroll bar?

**Comment by justineechen** [comment]
> if reader tried the docker services, and run the tests, testEmptyInventory() will fail

- The `InventoryEndpointTest.java` sends a `POST` request to `http://localhost:9081/inventory/systems/reset` which clears the inventory before the tests run
