### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microservices-docker#8]
- Need a better slug and repo name.

- Ensure title, abstract and introduction work with the Docker guide.

- Improve abstract: I find "by Docker" weird and what do we mean by "isolated containers"?

- Improve the first 2 introductory paragraphs.  Again, what do we mean by "isolated containers"?  Is it really to "accelerate your development" only?  I would describe what are containers, why containers, and then go on to touch on the focus on the guide.  Should indicate that we are using Docker as the containerization technology (example) in this guide.

- You’ll learn how to construct "a" Dockerfile?

- "This guide demonstrates how both microservices can be run and communicate in different isolated containers":  This is disjoint with the other paragraphs or the focus of the guide?

- "The <packageFile> tag in the pom.xml configures the microservices to be packed in an archive form":  Use "packaged" instead of "packed"?  Also, better explain what is in the package (archive) and what is it used for (in general)?

- What is the starting point?  "The starting point of the inventory service can be found at the http://localhost:9081/inventory/systems URL."  I found its use weird here.  I would consider making these few paragraphs more consistent with our other guides too.

- "To pull different open-liberty image, like kernel, you may define the FROM instructions as FROM open-liberty:kernel":  "instructions" should be "instruction" i.e. singular here?

- Can indicate that the images are non-root by default for security purpose.

- "Creating your Docker image":  I will use "Building" instead of "Creating"?

- "Run the following commands to build and containerize the application": Consider "Run the following commands to build container images for your application"?

- "The -t flag in the docker build command allows the docker image to be in name[:tag] format":  "Docker" instead of "docker"?

- Capitalize "D" in all instances of "Docker"?

- "You will find the [system-ip-address]":  Call this out as an example.  I think we can make this part of the guide flow better?  Should indicate what is "[system-ip-address]" better.

- "You can test your microservices manually or with automated tests that test the microservices running locally and against the docker container":  This sentence is convoluted.

- "You have just built Docker images for two microservices in Open Liberty": "in Open Liberty" is problematic?

**Comment by yeekangc** [comment]
@gkwan-ibm @justineechen ^^^

**Comment by justineechen** [comment]
> "The -t flag in the docker build command allows the docker image to be in name[:tag] format": "Docker" instead of "docker"?

> Capitalize "D" in all instances of "Docker"?

- The `docker` in `docker run` is in lower case because we're referencing the command, in other guides we have used lower case when we refer to the complete command that the user just executed.
In existing Docker guide:
<img width="561" alt="Screen Shot 2019-06-27 at 4 20 56 PM" src="https://user-images.githubusercontent.com/18709242/60347920-50f47e80-9973-11e9-9a74-2aced9198e98.png">

 @yeekangc Would it be okay to leave it as is?

- I will capitalize all other instances of "Docker" that do not reference Docker commands

**Comment by justineechen** [comment]
@gkwan-ibm @yeekangc 
Possible repo-names/slugs:
- guide-docker-image
- guide-docker-intro (rename guide-docker to something more specific to developing microservices)

**Comment by yeekangc** [comment]
The Docker commands themselves are fine without first-letter capitalization.  I was referring to the non-command instances.

**Comment by yeekangc** [comment]
What's the purpose of the <profile> section in the top-level POM file?

**Comment by yeekangc** [comment]
See #10 and #11 for my updates.  Can use another round of edits.

**Comment by yeekangc** [comment]
Good with the latest changes.  Closing.  Slug and repo name will be handled separately and resolved before publishing.

**Comment by yeekangc** [comment]
Just realized that I didn't get a response regarding `<profile>` in the POM file.  @justineechen, what is that for?
